### ISSUE TITLE
Read fast-node panic

### ISSUE THREAD

**Issue by giskook** [yihuang/python-iavl#1]
Hi @yihuang ,
       I want to use the tool to check the fast node value. I execute the follow command:

`nix --extra-experimental-features flakes --extra-experimental-features nix-command run github:yihuang/python-iavl -- fast-node --db ./.exchaind/data_repaired/application.db -s acc 015cf8cee27d59fe93cce6b1e9102fcc28e0e009fe
`

I got the panic

```
Traceback (most recent call last):
  File "/nix/store/mid39hf09gf1hbldzkas5vj6ab9kl5z6-python3.10-iavl-0.1.0/bin/.iavl-wrapped", line 9, in <module>
    sys.exit(cli())
  File "/nix/store/xz0y6j7rnih5imbk2ishfzwa7caz0kk9-python3.10-click-8.1.3/lib/python3.10/site-packages/click/core.py", line 1130, in __call__
    return self.main(*args, **kwargs)
  File "/nix/store/xz0y6j7rnih5imbk2ishfzwa7caz0kk9-python3.10-click-8.1.3/lib/python3.10/site-packages/click/core.py", line 1055, in main
    rv = self.invoke(ctx)
  File "/nix/store/xz0y6j7rnih5imbk2ishfzwa7caz0kk9-python3.10-click-8.1.3/lib/python3.10/site-packages/click/core.py", line 1657, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/nix/store/xz0y6j7rnih5imbk2ishfzwa7caz0kk9-python3.10-click-8.1.3/lib/python3.10/site-packages/click/core.py", line 1404, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/nix/store/xz0y6j7rnih5imbk2ishfzwa7caz0kk9-python3.10-click-8.1.3/lib/python3.10/site-packages/click/core.py", line 760, in invoke
    return __callback(*args, **kwargs)
  File "/nix/store/mid39hf09gf1hbldzkas5vj6ab9kl5z6-python3.10-iavl-0.1.0/lib/python3.10/site-packages/iavl/cli.py", line 68, in fast_node
    version, value, _ = decode_fast_node(bz)
  File "/nix/store/mid39hf09gf1hbldzkas5vj6ab9kl5z6-python3.10-iavl-0.1.0/lib/python3.10/site-packages/iavl/utils.py", line 175, in decode_fast_node
    version, n = cprotobuf.decode_primitive(bz[offset:], "sint64")
TypeError: 'NoneType' object is not subscriptable
```

Is my command wrong?
Thanks.
Kane

**Comment by yihuang** [comment]
Thanks for feedback, I guess it's just the fast-node cmd is not well tested, I'll have a look.

**Comment by yihuang** [comment]
I think the error just means the fast node don't exists for the key, I'll update the error message.

**Comment by giskook** [comment]
> I think the error just means the fast node don't exists for the key, I'll update the error message.

ok, thanks for your tool.

**Comment by yihuang** [comment]
done, closing now.
